config_cls: VoicingTTSPipelineConfig
# python -m sglang_omni.models.voicing_tts.convert_checkpoint Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice checkpoints/voicing-tts-12hz-1.7b-customvoice
model_path: checkpoints/voicing-tts-12hz-1.7b-customvoice
