config_cls: VoicingTTSPipelineConfig
# python -m sglang_omni.models.voicing_tts.convert_checkpoint Qwen/Qwen3-TTS-12Hz-0.6B-Base checkpoints/voicing-tts-12hz-0.6b-base
model_path: checkpoints/voicing-tts-12hz-0.6b-base
