config_cls: VoicingTTSPipelineConfig
# python -m sglang_omni.models.voicing_tts.convert_checkpoint Qwen/Qwen3-TTS-12Hz-1.7B-Base checkpoints/voicing-tts-12hz-1.7b-base
model_path: checkpoints/voicing-tts-12hz-1.7b-base
